// Includes 1200 boy's names and just under 1000 girl's names
// Also 250 cocktails


// form can be
// "is", "are", "has" to indicate the phrase can follow "she is" etc.
// "iso" to indicate a complete phrase, including verb
erotica.smallBustFeature = { type:'bust', form:'has', s:'{random:modest tits:slight breasts:little in the way of tits:small tits:hardly any boobs}'},
erotica.bigBustFeature = { type:'bust', form:'has', s:'{random:impressive:good-sized:great} {random:tits:boobs}'},
erotica.hugeBustFeature = { type:'bust', form:'has', s:'{random:large:huge} {random:tits:gazongas:jugs}'},

erotica.smallCockFeature = { type:'cock', form:'has', bp:'cock', s:'a {random:small:less than impressive:disappointing} {random:willy:todger}'},
erotica.bigCockFeature = { type:'cock', form:'has', bp:'cock', s:'a {random:impressive:good-sized:great} {random:cock:dick}'},
erotica.hugeCockFeature = { type:'cock', form:'has', bp:'cock', s:'a {random:large:huge} {random:cock:dick}'},


erotica.maleFeatures = []
erotica.femaleFeatures = []


erotica.femaleFeatures.small = { type:'size', form:'is', s:'{random:a small woman:small:petite:a petite woman}'},
erotica.femaleFeatures.big = { type:'size', form:'is', s:'{random:a tall woman:tall:Amazonian in stature}'},
erotica.maleFeatures.small = { type:'size', form:'is', s:'{random:not so tall:on the short side:below average height}'},
erotica.maleFeatures.big = { type:'size', form:'is', s:'{random:a tall guy:tall:statuesque}'},

erotica.femaleFeatures.hot = { type:'attraction', form:'is', s:'{random:attractive:good-looking:sexy:alluring:beautiful:very good-looking}'},
erotica.femaleFeatures.superHot = { type:'attraction', form:'is', s:'{random:super hot::stunning:amazingly attractive:so beautiful:drop-dead gorgeous}'},

erotica.maleFeatures.hot = { type:'attraction', form:'is', s:'{random:handsome:good-looking:an attractive guy}'},
erotica.maleFeatures.superHot = { type:'attraction', form:'is', s:'{random:super hot:very handsome:very good-looking:stunning:drop-dead gorgeous}'},





erotica.features = [
  { type:'mouth', form:'has', bp:'mouth', s:'a broad mouth'},
  { type:'mouth', form:'has', bp:'mouth', s:'a wide mouth'},
  { type:'mouth', form:'has', bp:'mouth', s:'a narrow mouth'},
  { type:'mouth', form:'has', bp:'mouth', s:'a broad mouth'},
  { type:'mouth', form:'has', bp:'mouth', s:'a pouting mouth'},
  { type:'mouth', form:'has', bp:'mouth', s:'pursed lips'},
  { type:'mouth', form:'has', bp:'mouth', s:'side lips'},
  { type:'mouth', form:'has', bp:'mouth', s:'thin lips'},
  { type:'mouth', form:'has', bp:'mouth', s:'pursed lips'},
  
  { type:'expression', form:'has', bp:'face', s:'a hostile expression'},
  { type:'expression', form:'has', bp:'face', s:'a wary expression'},
  { type:'expression', form:'has', bp:'face', s:'a severe expression'},
  { type:'expression', form:'has', bp:'face', s:'a harsh expression'},
  { type:'expression', form:'has', bp:'face', s:'a vacant expression'},
  { type:'expression', form:'is', bp:'face', s:'smiling'},
  { type:'expression', form:'is', bp:'face', s:'scowling'},
  { type:'expression', form:'is', bp:'face', s:'frowning'},

  { type:'eyebrows', form:'has', bp:'face', s:'arched eyebrows'},
  { type:'eyebrows', form:'has', bp:'face', s:'thick eyebrows'},
  { type:'eyebrows', form:'has', bp:'face', s:'faint eyebrows'},
  { type:'eyebrows', form:'has', bp:'face', s:'rounded eyebrows'},
  { type:'eyebrows', form:'has', bp:'face', s:'straight eyebrows'},
  { type:'eyebrows', form:'has', bp:'face', s:'faint eyebrows'},
  { type:'eyebrows', form:'has', bp:'face', s:'high eyebrows'},
  { type:'eyebrows', form:'has', bp:'face', s:'shirt eyebrows'},
  { type:'eyebrows', form:'has', bp:'face', s:'long eyebrows'},
  
  { type:'nose', form:'has', bp:'face', s:'a pert nose'},
  { type:'nose', form:'has', bp:'face', s:'a fleshy nose'},
  { type:'nose', form:'has', bp:'face', s:'a turned-up nose'},
  { type:'nose', form:'has', bp:'face', s:'a snub nose'},
  { type:'nose', form:'has', bp:'face', s:'a Roman nose'},
  { type:'nose', form:'has', bp:'face', s:'a hawk nose'},
  { type:'nose', form:'has', bp:'face', s:'a Greek nose'},
  { type:'nose', form:'has', bp:'face', s:'a Nubian nose'},
  { type:'nose', form:'has', bp:'face', s:'a bony nose'},
  { type:'nose', form:'has', bp:'face', s:'a small nose'},
  { type:'nose', form:'has', bp:'face', s:'a soft, petite nose'},
  { type:'nose', form:'has', bp:'face', s:'a bony nose'},
  { type:'nose', form:'has', bp:'face', s:'an aquiline nose'},
  { type:'nose', form:'has', bp:'face', s:function(char) { return "a slight indentation in the tip of " + char.pronouns.poss_adj + " nose"}},

  { type:'body', form:'has', s:'a muscled body'},
  { type:'body', form:'has', ifHas:'cock', s:'a muscled body'},
  { type:'body', form:'has', ifHas:'cock', s:'a broad chest'},
  { type:'body', form:'has', ifHas:'cock', s:'impressive abs'},
  { type:'body', form:'has', ifHas:'cock', s:'a very muscled body'},
  { type:'body', form:'has', ifHas:'tit', s:'long legs'},
  { type:'body', form:'has', ifHas:'tit', s:'long legs'},
  { type:'body', form:'has', ifHas:'tit', s:'long legs'},
  { type:'body', form:'has', ifHas:'tit', s:'great legs'},
  { type:'body', form:'has', ifHas:'tit', s:'hot legs'},

]

erotica.maleFeatures.features = erotica.features
erotica.femaleFeatures.features = erotica.features






// ---- EYES ---

erotica.eyeColors = [
  "amber",
  "blue",
  "deeo blue",
  "pale blue",
  "aquamarine",
  "brown",
  "brown",
  "brown",
  "brown",
  "brown",
  "gray",
  "green",
  "hazel",
]

erotica.eyeFeatureGeneric = { type:'eyes', form:'has', bp:'face', s:function(char) { return char.eyeColor + ' eyes'}},
erotica.maleFeatures.eyeGeneric = erotica.eyeFeatureGeneric
erotica.femaleFeatures.eyeGeneric = erotica.eyeFeatureGeneric

erotica.eyeFeatures = [
  { type:'eyes', form:'has', bp:'face', s:function(char) { return 'upturned ' + char.eyeColor + ' eyes'}},
  { type:'eyes', form:'has', bp:'face', s:function(char) { return 'downturned ' + char.eyeColor + ' eyes'}},
  { type:'eyes', form:'has', bp:'face', s:function(char) { return 'warm ' + char.eyeColor + ' eyes'}},
  { type:'eyes', form:'has', bp:'face', s:function(char) { return 'friendly ' + char.eyeColor + ' eyes'}},
  { type:'eyes', form:'has', bp:'face', s:function(char) { return 'doleful ' + char.eyeColor + ' eyes'}},
  { type:'eyes', form:'has', bp:'face', s:function(char) { return 'doe-like ' + char.eyeColor + ' eyes'}},
  { type:'eyes', form:'has', bp:'face', s:function(char) { return 'soulful ' + char.eyeColor + ' eyes'}},
  { type:'eyes', form:'has', bp:'face', s:function(char) { return 'almond-shaped ' + char.eyeColor + ' eyes'}},
  { type:'eyes', form:'has', bp:'face', s:function(char) { return 'moon-shaped ' + char.eyeColor + ' eyes'}},
  { type:'eyes', form:'has', bp:'face', s:function(char) { return 'sparkling ' + char.eyeColor + ' eyes'}},
  { type:'eyes', form:'has', bp:'face', s:function(char) { return 'staring ' + char.eyeColor + ' eyes'}},
  { type:'eyes', form:'has', bp:'face', s:function(char) { return 'scary ' + char.eyeColor + ' eyes'}},
]
  
erotica.maleFeatures.eye = erotica.eyeFeatures
erotica.femaleFeatures.eye = erotica.eyeFeatures





// ---- SKIN TONE ---

erotica.skinToneFeatures = [
  { type:'skintone', form:'has', s:function(char) { return char.skinTone + " skin"}},
  { type:'skintone', form:'has', s:function(char) { return "a " + char.skinTone + " skin tone"}},
  { type:'skintone', form:'iso', s:function(char) { return sentenceCase(char.pronouns.poss_adj) + " skin is " + char.skinTone}},
]

erotica.paleSkinTones = [
  "pale",
  "very pale",
  "almost white",
  "milky white",
  "alabaster",
]

erotica.skinTones = [
  "umber",
  "dark yellow-brown",
  "sepia",
  "reddish-brown",
  "ochre",
  "russet",
  "terra-cotta",
  "deep lustrous yellow-brown",
  "tawny",
  "taupe",
  "khaki",
  "fawn",
  "beige",
  "warm beige",
  "tanned brown",
  "creamy beige",
  "warm brown",
  "bronze",
  "copper",
  "sable",
  "mahogany",
  "chestnut",
  "very dark",
  "almost black",
]







// ---- HAIR ---

erotica.naturalHairColors = [
  "raven black",
  "black",
  "black",
  "black",
  "deepest brunette",
  "dark brown",
  "medium brown",
  "brunette",
  "light brown",
  "chestnut brown",
  "walnut brown",
  "light chestnut brown",
  "caramel brown",
  "auburn",
  "ginger red",
  "copper",
  "titian",
  "strawberry blond",
  "light blonde",
  "golden blonde",
  "medium blonde",
  "platinum blonde",
  "blue",
  "brunette",
  "ginger",
  "orange",
  "platinum",
]

erotica.redHairColors = [
  "auburn",
  "ginger red",
  "copper",
  "titian",
  "strawberry blond",
  "ginger",
]

erotica.altHairColors = [
  "pink",
  "shocking pink",
  "violet",
  "purple",
  "mauve",
  "blue",
  "electric blue",
  "bright red",
  "bright yellow",
  "bright green",
]
  // Hair length
  // 0 Shaved
  // 1 buzzcut
  // 2 crewcut, inch or so
  // 3 
  // 4
  // 5 shoulder length
  // 6 armpit
  // 7 lower boob
  // 8 naval
  // 9 waist
  // 10 crotch
erotica.femaleFeatures.hairStyles = [
  
  // long hair (6-10)
  { type:'hair', hairLength:8, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair cascading down " + char.pronouns.poss_adj + " back"}},
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return "wavy long " + char.hairColor + " hair"}},
  { type:'hair', hairLength:6, form:'has', bp:'head', s:function(char) { return "long, wild " + char.hairColor + " hair"}},
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return "long, tousled " + char.hairColor + " hair"}},
  { type:'hair', hairLength:8, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair"}},
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair in cornrow braids"}},
  { type:'hair', hairLength:6, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair swept to the left"}},
  { type:'hair', hairLength:6, form:'has', bp:'head', s:function(char) { return "right-swept " + char.hairColor + " hair"}},
  { type:'hair', hairLength:9, form:'has', bp:'head', s:function(char) { return "long, layered " + char.hairColor + " hair falling down her back"}},
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return "sleek, straight and long " + char.hairColor + " hair"}},
  { type:'hair', hairLength:6, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in long glamorous waves"}},
  { type:'hair', hairLength:9, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair tumbling down " + char.pronouns.poss_adj + " back"}},
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return "wavy long " + char.hairColor + " hair"}},
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return "long, wild " + char.hairColor + " hair"}},
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return "long, tousled " + char.hairColor + " hair"}},
  { type:'hair', hairLength:8, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair"}},
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return "long cornrow-braided " + char.hairColor + " hair"}},
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair swept to the left"}},
  { type:'hair', hairLength:6, form:'has', bp:'head', s:function(char) { return "right-swept " + char.hairColor + " hair"}},
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return "long, layered " + char.hairColor + " hair falling to " + char.pronouns.poss_adj + " waist"}},
  { type:'hair', hairLength:10, form:'has', bp:'head', s:function(char) { return "long, wild " + char.hairColor + " hair falling to well below " + char.pronouns.poss_adj + " waist"}},
  { type:'hair', hairLength:8, form:'has', bp:'head', s:function(char) { return "long, sleek and straight " + char.hairColor + " hair"}},
  { type:'hair', hairLength:6, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in long glamorous waves"}},

  // ponytail, etc. (5-8)
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in braids"}},
  { type:'hair', hairLength:8, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair in braids"}},
  { type:'hair', hairLength:5, form:'has', bp:'head', s:function(char) { return char.pronouns.poss_adj + "long " + char.hairColor + " hair in a high ponytail"}},
  { type:'hair', hairLength:8, form:'has', bp:'head', s:function(char) { return char.pronouns.poss_adj + "long " + char.hairColor + " hair in a high ponytail that falls halfway down " + char.pronouns.poss_adj + " back"}},
  { type:'hair', hairLength:5, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair held in a tight ponytail"}},
  { type:'hair', hairLength:6, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair held in a ponytail"}},
  { type:'hair', hairLength:6, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair in a neat ponytail"}},
  { type:'hair', hairLength:5, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a half-ponytail"}},
  { type:'hair', hairLength:6, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a side-ponytail"}},
  { type:'hair', hairLength:5, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in two pigtails"}},
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in long pigtails"}},
  
  // short hair (1-5)
  { type:'hair', hairLength:5, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair that brushes " + char.pronouns.poss_adj + " shoulders"}},
  { type:'hair', hairLength:3, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a short fro"}},
  { type:'hair', hairLength:4, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a short bob"}},
  { type:'hair', hairLength:4, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a bob"}},
  { type:'hair', hairLength:5, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a bob with outward curls"}},
  { type:'hair', hairLength:5, form:'has', bp:'head', s:function(char) { return "slicked-back, shoulder-length " + char.hairColor + " hair"}},
  { type:'hair', hairLength:5, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a shoulder-grazing bob"}},
  { type:'hair', hairLength:5, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a curly bob"}},
  { type:'hair', hairLength:2, form:'has', bp:'head', s:function(char) { return "pixie-cut " + char.hairColor + " hair"}},
  { type:'hair', hairLength:1, form:'has', bp:'head', s:function(char) { return "buzz-cut " + char.hairColor + " hair"}},
  { type:'hair', hairLength:2, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a crew-cut"}},
  { type:'hair', hairLength:2, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a short, Mohawk-style"}},
  { type:'hair', hairLength:5, form:'has', bp:'head', s:function(char) { return char.pronouns.poss_adj + " " + char.hairColor + " hair in a halo of curls"}},
]

erotica.maleFeatures.hairStyles = [
  
  // long hair (6-10)
  { type:'hair', hairLength:8, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair cascading down " + char.pronouns.poss_adj + " back"}},
  { type:'hair', hairLength:7, form:'has', bp:'head', s:function(char) { return "wavy long " + char.hairColor + " hair"}},
  { type:'hair', hairLength:6, form:'has', bp:'head', s:function(char) { return "long, wild " + char.hairColor + " hair"}},

  // ponytail, etc. (5-8)
  { type:'hair', hairLength:6, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair held in a ponytail"}},
  { type:'hair', hairLength:6, form:'has', bp:'head', s:function(char) { return "long " + char.hairColor + " hair in a neat ponytail"}},
  
  // short hair (1-5)
  { type:'hair', hairLength:5, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair that brushes " + char.pronouns.poss_adj + " shoulders"}},
  { type:'hair', hairLength:3, form:'has', bp:'head', s:function(char) { return "slicked-back " + char.hairColor + " hair"}},
  { type:'hair', hairLength:1, form:'has', bp:'head', s:function(char) { return "buzz-cut " + char.hairColor + " hair"}},
  { type:'hair', hairLength:1, form:'has', bp:'head', s:function(char) { return "buzz-cut " + char.hairColor + " hair"}},
  { type:'hair', hairLength:1, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a buzz-cut"}},
  { type:'hair', hairLength:2, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a crew-cut"}},
  { type:'hair', hairLength:2, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a flat-top"}},
  { type:'hair', hairLength:2, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a short, Mohawk-style"}},
  { type:'hair', hairLength:4, form:'has', bp:'head', s:function(char) { return char.hairColor + " hair in a high Mohawk-style"}},
  { type:'hair', hairLength:2, form:'has', bp:'head', s:function(char) { return "spiky " + char.hairColor + " hair"}},

  { type:'hair', hairLength:0, form:'has', bp:'head', s:function(char) { return "a shaven head"}},
  { type:'hair', hairLength:0, form:'has', bp:'head', s:function(char) { return "a shaven head"}},
  { type:'hair', hairLength:0, form:'has', bp:'head', s:function(char) { return "a shaven head"}},

]






// ---- TATTOOS ---

erotica.femaleFeatures.tattoos = [
  
  { type:'tattoo', form:'has', s:function(char) { return "tattoos all over " + char.pronouns.poss_adj + " body"}},

  { type:'tattoo', form:'has', bp:'upperback', script:erotica.setTattooImage, s:function(char) {
    return char.tattooImage + " tattooed on " + char.pronouns.poss_adj + " left shoulder blade"
  }},

  { type:'tattoo', form:'has', bp:'lowerback', script:erotica.setTattooImage, s:function(char) {
    return char.tattooImage + " tattooed on " + char.pronouns.poss_adj + " lower back"
  }},

  { type:'tattoo', form:'has', bp:'midriff', script:erotica.setTattooImage, s:function(char) {
    return char.tattooImage + " tattooed on " + char.pronouns.poss_adj + " her midriff"
  }},

  { type:'tattoo', form:'has', bp:'tit', script:erotica.setTattooImage, s:function(char) {
    return char.tattooImage + " tattooed on " + char.pronouns.poss_adj + " left breast"
  }},

  { type:'tattoo', form:'has', bp:'buttock', script:erotica.setTattooImage, s:function(char) {
    return char.tattooImage + " tattooed on " + char.pronouns.poss_adj + " left buttock"
  }},


  { type:'tattoo', form:'has', bp:'thigh', script:erotica.setTattooQuote, s:function(char) {
    return "the words \"" + char.tattooQuote + "\" tattooed on " + char.pronouns.poss_adj + " left thigh"
  }},

  { type:'tattoo', form:'has', bp:'arm', script:erotica.setTattooQuote, s:function(char) {
    return "the words \"" + char.tattooQuote + "\" tattooed on " + char.pronouns.poss_adj + " left arm"
  }},

  { type:'tattoo', form:'has', bp:'midriff', script:erotica.setTattooQuote, s:function(char) {
    return "the words \"" + char.tattooQuote + "\" tattooed just above " + char.pronouns.poss_adj + " waist"
  }},
]

erotica.maleFeatures.tattoos = [
  
  { type:'tattoo', form:'has', bp:'arm', s:function(char) { return "large tribal tattoos covering both " + char.pronouns.poss_adj + " arms"}},
  { type:'tattoo', form:'has', s:function(char) { return "tattoos all over " + char.pronouns.poss_adj + " body"}},

  { type:'tattoo', form:'has', bp:'upperback', script:erotica.setTattooImage, s:function(char) {
    return char.tattooImage + " tattooed on " + char.pronouns.poss_adj + " back"
  }},

  { type:'tattoo', form:'has', bp:'chest', script:erotica.setTattooImage, s:function(char) {
    return char.tattooImage + " tattooed on " + char.pronouns.poss_adj + " chest"
  }},

  { type:'tattoo', form:'has', bp:'midriff', script:erotica.setTattooImage, s:function(char) {
    return char.tattooImage + " tattooed on " + char.pronouns.poss_adj + " stomach"
  }},

  { type:'tattoo', form:'has', bp:'arm', script:erotica.setTattooImage, s:function(char) {
    return char.tattooImage + " tattooed on " + char.pronouns.poss_adj + " upper left arm"
  }},

  { type:'tattoo', form:'has', bp:'arm', script:erotica.setTattooImage, s:function(char) {
    return char.tattooImage + " tattooed on " + char.pronouns.poss_adj + " upper right arm"
  }},

  { type:'tattoo', form:'has', bp:'buttock', script:erotica.setTattooImage, s:function(char) {
    return char.tattooImage + " tattooed on " + char.pronouns.poss_adj + " left buttock"
  }},


  { type:'tattoo', form:'has', bp:'thigh', script:erotica.setTattooQuote, s:function(char) {
    return "the words \"" + char.tattooQuote + "\" tattooed on " + char.pronouns.poss_adj + " right arm"
  }},

]

erotica.tattooImages = [
  "a fiery scorpion",
  "a colorful bird with its wings spread",
  "a tiger's head",
  "a roaring tiger",
  "three wolves",
  "wolves howling at the moon",
  "a lion's head",
  "an elephant head",
  "a serpentine dragon",
  "fire-breathing dragon",
  "a dragon coiled around a naked woman",
  "a pheonix, wings spread",
  "a pheonix rising from flames",
  "Pegasus",
  "an angel",
  "two entwined snakes",
  "an eagle",
  
  "an army of fire-eyed skeletons",
  "a fiery skull",
  "a skull and dagger",
  "a skull wearing a crown",
  "a crown",
  "some dollar bills",
  "a rose",
  "a crying rose",
  "a rose dripping blood",
  "a sunflower",
  "an oak tree",
  "a revolver and a rose",
  "an assault rifle",
  "an AK-47",
  "the gates of hell",
  "meticulously drawn feathers",
  "some Chinese characters",
]

erotica.tattooQuotes = [
  "For the eyes of the Lord are over the righteous and his ears are open…",
  "Take care of the sense, and the sounds will take care of themselves.",
  "Even angels fall",
  "My life is my art, My art is my life",
  "Live by faith, not by sight",
  "Love me for who I am",
  "Too wild to live, too rare to die",
  "We accept the love, we think we deserve",
  "How sweet the sound",
  "Death leaves a heartache no one can heal.  Love bears a memory no one can steal.",
  "I should have been a pair of ragged claws, scuttling across the floors of silent seas.",
  "As it was in the beginning one love so shall it be in the end one heart.",
  "When you left me behind you set me free.",
  "She said lose your eyes and free your mind, you’re free to fly.",
  "There is a change for the hearing of my heart.  It really goes.",
  "Life’s roughest storms prove the strength of our anchors.",
  "Float like a butterfly, sting like a bee.",
  "Dream as if you’ll live forever.  Live as if you’ll die today.",
  "We must all face the choice between what is right and what is easy.",
  "Have faith",
  "Family like branches on a tree, we all grow in different directions.",
  "By the strength within I shall succeed.",
  "Don’t worry be happy",
  "My soul corrupted by vengeance hath endured torment…",
  "She is too fond of books, and it has turned her brain.",
  "And though she be but little, she is fierce",
  "Happiness depends upon ourselves.",
  "So dear love him,that with him all deaths could endure…",
  "Beneath the makeup and behind the smile, I am just a girl…",
  "For every dark night, there’s a brighter day.",
  "Do not go gentle into that good night…",
  "In the beginning, God created the heavens and the earth.",
  "Don’t dream your life, live your dream.",
  "Sometimes when you fall you fly",
  "Through every dark night, there is a brighter day",
  "Some say I’m going the wrong way…",
  "Take a breath and be strong",
  "It’s only life after all",
  "Flowers only last so long",
  "The ultimate measure of a man is not who he stands in the moments of comfort…",
  "The greatest thing you’ll ever learn is just to love and be loved in return.",
  "Do what you love",
  "With His love there is nothing I cannot do.",
  "Every moment overflows with power, 66 thousand miles an hour.",
  "You be the Anchor that keeps my feet on the ground… and I’ll be the wings….",
  "Hate without reason",
  "Who is more real?",
  "Life goes on",
  "... and the world will be yours",
  "You believe lies so you must learn to trust no one but yourself.",
  "Get busy living or get busy dying",
  "We are the graceless and dumbfounded, insane with our own insatiable desire…",
  "Don’t test the ones you love, it will only tear us down.",
  "If you want peace, prepare for war",
  "Lead me not into temptation",
  "Walk by faith, not by sight",
  "Beneath lay words that suffocate",
  "If you don’t live for something, you’ll die for nothing",
  "She flies by her own wings",
  "Art never comes from happiness",
  "This is your life and it’s ending one minute at a time…",
  "When the power of love overcomes the love of power then the world will know peace",
  "Dream as if you’ll live forever",
  "Even though I walk through the valley of the shadow of death…",
  "Reality is wrong, dreams are for real",
  "If I lay here if I just lay here, would you lie with me…",
  "You get what you give",
  "It’s only forever… not long at all",
  "In love and death",
  "In a world of my own",
  "This too shall pass",
  "What type of harvest will September bring",
  "Life is not measured by the number of breaths…",
  "Fate fell short",
  "Never a failure always a lesson.",
  "Betrayer, where is your head. Betrayer, where is your heart.",
  "Until forever fades away",
  "Fear is the mind killer",
  "Strength Respect Loyalty",
  "Hope Love Family Believe Strength Dream",
  "Dear lover, give me one last painful kiss",
  "Never compromise. Not even in the face of armageddon.",
  "Heart means everything",
  "Never forget who you are",
  "Grant me the serenity to accept the things I cannot change…",
  "You are what you love and not what loves you back",
  "Wars begin in the minds of men",
  "If you can dream it you can do it",
  "With pain comes strength",
  "To die would be an awfully big adventure",
  "Be the one to guide me but never hold me down",
  "I will fear no evil for you are with me",
  "Live each day as if it were your last",
  "Faith Hope and Love",
  "She was no more no less, than anything but herself",
  "Dream Believe Dare Do",
  "Just as long as there are stars above us",
  "A prayer for the wild at heart, kept in cages",
  "To err is human; to forgive is divine.",
  "Uncertain, intrepid, possibly immortal decidedly in love",
  "I brought down the sky for you but all you did was shrug",
  "Forget your past, forgive yourself, and begin again",
  "You don’t know what you’re alive for until you know what you would die for",
  "Fearfully and wonderfully made",
  "To sleep, perchance to dream…",
  "Be the change",
  "The worst part about being lied to is knowing you weren’t worth the truth",
  "I listened to the brag of my heart I am I am I am",
  "Miss me little but not too long.",
  "One Life One Love",
]






// ---- OLD AND UNUSED ---

erotica.piercings = [
  "no piercings",
  "a drop earring with a diamond",
  "dangle earrings in each ear",
  "dangle earrings in each ear and a diamond nose stud",
  "two gold hoops in each ear, one in the lower lip, one the nose",
  "five gold hoops in each ear, one in the lower lip, one the nose, one the navel and one on each nipple",
]

erotica.icons = [
  "a panda",
  "a tiger",
  "a dolphin",
  "a T. rex",
  "a chameleon",
  "a fat cat",
  "a lobster",
  "a snake",
  "two pigs, fucking",
  "a stylised alien",
  "a Hindu goddess with eight arms",
  "a red demon with horns",
  "a demon with a big cock",
  "a zombie",
  "a sunflower",
  "a stylised tree",
  "an oak tree",
  "a large banana",
  "a turnip with a face",
  "a skull",
  "a heart with a dagger in it",
  "a screaming face",
  "a lightning strike",
  "a cock",
  "a dildo",
  "a lacy bra",
  "a pair of handcuffs",
  "a Dali-esque melting clock",
  "the number 69 written",
  "\"I like slutz\" written",
  "\"Frank says FUCK\" in big writing",
  "planet Earth",
  "a solar eclipse",
  "an erupting volcano",
  "a guitar",
  "the silhouette of a naked woman",
  "a pot of ink with a quill in it",
  "artful blobs of colour",
  "a lightning strike",
  "the Whitehouse",
  "the Eiffel Tower",
  "the Seattle skyline",
  "the London tube map",
  "the DNA molecule",
  "a half full pint of beer",
  "a pizza slice",
]








// ---- NAMES ---

erotica.boysNames = [
  "Aaron",
  "Abdul",
  "Abe",
  "Abel",
  "Abraham",
  "Abram",
  "Adalberto",
  "Adam",
  "Adan",
  "Adolfo",
  "Adolph",
  "Adrian",
  "Agustin",
  "Ahmad",
  "Ahmed",
  "Al",
  "Alan",
  "Albert",
  "Alberto",
  "Alden",
  "Aldo",
  "Alec",
  "Alejandro",
  "Alex",
  "Alexander",
  "Alexis",
  "Alfonso",
  "Alfonzo",
  "Alfred",
  "Alfredo",
  "Ali",
  "Allan",
  "Allen",
  "Alonso",
  "Alonzo",
  "Alphonse",
  "Alphonso",
  "Alton",
  "Alva",
  "Alvaro",
  "Alvin",
  "Amado",
  "Ambrose",
  "Amos",
  "Anderson",
  "Andre",
  "Andreas",
  "Andres",
  "Andrew",
  "Andy",
  "Angelo",
  "Anibal",
  "Anthony",
  "Antione",
  "Antoine",
  "Anton",
  "Antone",
  "Antonio",
  "Antony",
  "Antwan",
  "Archie",
  "Arden",
  "Ariel",
  "Arlen",
  "Arlie",
  "Armand",
  "Armando",
  "Arnold",
  "Arnoldo",
  "Arnulfo",
  "Aron",
  "Arron",
  "Art",
  "Arthur",
  "Arturo",
  "Asa",
  "Aubrey",
  "August",
  "Augustine",
  "Augustus",
  "Aurelio",
  "Austin",
  "Avery",
  "Barney",
  "Barrett",
  "Barry",
  "Bart",
  "Barton",
  "Basil",
  "Beau",
  "Ben",
  "Benedict",
  "Benito",
  "Benjamin",
  "Bennett",
  "Bennie",
  "Benny",
  "Benton",
  "Bernard",
  "Bernardo",
  "Bernie",
  "Berry",
  "Bert",
  "Bertram",
  "Bill",
  "Billy",
  "Blaine",
  "Blair",
  "Blake",
  "Bo",
  "Bob",
  "Bobby",
  "Booker",
  "Boris",
  "Boyce",
  "Boyd",
  "Brad",
  "Bradford",
  "Bradley",
  "Bradly",
  "Brady",
  "Brain",
  "Branden",
  "Brandon",
  "Brant",
  "Brendan",
  "Brendon",
  "Brent",
  "Brenton",
  "Bret",
  "Brett",
  "Brian",
  "Brice",
  "Britt",
  "Brock",
  "Broderick",
  "Brooks",
  "Bruce",
  "Bruno",
  "Bryan",
  "Bryant",
  "Bryce",
  "Bryon",
  "Buck",
  "Bud",
  "Buddy",
  "Buford",
  "Burl",
  "Burt",
  "Burton",
  "Buster",
  "Byron",
  "Caleb",
  "Calvin",
  "Cameron",
  "Carey",
  "Carl",
  "Carlo",
  "Carlos",
  "Carlton",
  "Carmelo",
  "Carmine",
  "Carrol",
  "Carroll",
  "Carson",
  "Carter",
  "Cary",
  "Cecil",
  "Cedric",
  "Cedrick",
  "Cesar",
  "Chad",
  "Chadwick",
  "Chance",
  "Chang",
  "Charles",
  "Charley",
  "Charlie",
  "Chas",
  "Chase",
  "Chauncey",
  "Chester",
  "Chet",
  "Chi",
  "Chong",
  "Chris",
  "Christian",
  "Christoper",
  "Christopher",
  "Chuck",
  "Chung",
  "Clair",
  "Clarence",
  "Clark",
  "Claud",
  "Claude",
  "Claudio",
  "Clay",
  "Clayton",
  "Clement",
  "Clemente",
  "Cletus",
  "Cleveland",
  "Cliff",
  "Clifford",
  "Clifton",
  "Clint",
  "Clinton",
  "Clyde",
  "Cody",
  "Colby",
  "Cole",
  "Coleman",
  "Colin",
  "Collin",
  "Colton",
  "Columbus",
  "Conrad",
  "Cordell",
  "Corey",
  "Cornelius",
  "Cornell",
  "Cortez",
  "Cory",
  "Coy",
  "Craig",
  "Cristobal",
  "Cristopher",
  "Cruz",
  "Curt",
  "Curtis",
  "Cyril",
  "Cyrus",
  "Dallas",
  "Dalton",
  "Damian",
  "Damien",
  "Damion",
  "Damon",
  "Dan",
  "Dane",
  "Danial",
  "Daniel",
  "Danilo",
  "Dannie",
  "Danny",
  "Dante",
  "Darell",
  "Daren",
  "Darin",
  "Dario",
  "Darius",
  "Darnell",
  "Daron",
  "Darrel",
  "Darrell",
  "Darren",
  "Darrick",
  "Darrin",
  "Darron",
  "Darryl",
  "Darwin",
  "Daryl",
  "Dave",
  "David",
  "Davis",
  "Dean",
  "Deandre",
  "Deangelo",
  "Del",
  "Delbert",
  "Delmar",
  "Delmer",
  "Demarcus",
  "Demetrius",
  "Denis",
  "Dennis",
  "Denny",
  "Denver",
  "Deon",
  "Derek",
  "Derick",
  "Derrick",
  "Deshawn",
  "Desmond",
  "Devin",
  "Devon",
  "Dewayne",
  "Dewey",
  "Dewitt",
  "Dexter",
  "Dick",
  "Diego",
  "Dillon",
  "Dino",
  "Dion",
  "Dirk",
  "Domenic",
  "Domingo",
  "Dominic",
  "Dominick",
  "Don",
  "Donald",
  "Dong",
  "Donn",
  "Donnell",
  "Donnie",
  "Donny",
  "Donovan",
  "Donte",
  "Dorian",
  "Dorsey",
  "Doug",
  "Douglas",
  "Douglass",
  "Doyle",
  "Drew",
  "Duane",
  "Dudley",
  "Duncan",
  "Dustin",
  "Dusty",
  "Dwain",
  "Dwayne",
  "Dwight",
  "Dylan",
  "Earl",
  "Earle",
  "Earnest",
  "Ed",
  "Eddie",
  "Eddy",
  "Edgar",
  "Edgardo",
  "Edison",
  "Edmond",
  "Edmund",
  "Edmundo",
  "Eduardo",
  "Edward",
  "Edwardo",
  "Edwin",
  "Efrain",
  "Efren",
  "Elbert",
  "Elden",
  "Eldon",
  "Eldridge",
  "Eli",
  "Elias",
  "Elijah",
  "Eliseo",
  "Elisha",
  "Elliot",
  "Elliott",
  "Ellis",
  "Ellsworth",
  "Elmer",
  "Elmo",
  "Eloy",
  "Elroy",
  "Elton",
  "Elvin",
  "Elvis",
  "Elwood",
  "Emanuel",
  "Emerson",
  "Emery",
  "Emil",
  "Emile",
  "Emilio",
  "Emmanuel",
  "Emmett",
  "Emmitt",
  "Emory",
  "Enoch",
  "Enrique",
  "Erasmo",
  "Eric",
  "Erich",
  "Erick",
  "Erik",
  "Ernest",
  "Ernesto",
  "Ernie",
  "Errol",
  "Ervin",
  "Erwin",
  "Esteban",
  "Ethan",
  "Eugene",
  "Eugenio",
  "Eusebio",
  "Evan",
  "Everett",
  "Everette",
  "Ezekiel",
  "Ezequiel",
  "Ezra",
  "Fabian",
  "Faustino",
  "Fausto",
  "Federico",
  "Felipe",
  "Felix",
  "Felton",
  "Ferdinand",
  "Fermin",
  "Fernando",
  "Fidel",
  "Filiberto",
  "Fletcher",
  "Florencio",
  "Florentino",
  "Floyd",
  "Forest",
  "Forrest",
  "Foster",
  "Francesco",
  "Francis",
  "Francisco",
  "Frank",
  "Franklin",
  "Franklyn",
  "Fred",
  "Freddie",
  "Freddy",
  "Frederic",
  "Frederick",
  "Fredric",
  "Fredrick",
  "Freeman",
  "Fritz",
  "Gabriel",
  "Galen",
  "Garfield",
  "Garland",
  "Garret",
  "Garrett",
  "Garry",
  "Garth",
  "Gary",
  "Gaston",
  "Gavin",
  "Gaylord",
  "Genaro",
  "Gene",
  "Geoffrey",
  "George",
  "Gerald",
  "Geraldo",
  "Gerard",
  "Gerardo",
  "German",
  "Gerry",
  "Gil",
  "Gilbert",
  "Gilberto",
  "Gino",
  "Giovanni",
  "Giuseppe",
  "Glen",
  "Glenn",
  "Gonzalo",
  "Gordon",
  "Grady",
  "Graham",
  "Graig",
  "Grant",
  "Granville",
  "Greg",
  "Gregg",
  "Gregorio",
  "Gregory",
  "Grover",
  "Guillermo",
  "Gus",
  "Gustavo",
  "Guy",
  "Hai",
  "Hal",
  "Hank",
  "Hans",
  "Harlan",
  "Harland",
  "Harley",
  "Harold",
  "Harris",
  "Harrison",
  "Harry",
  "Harvey",
  "Hassan",
  "Hayden",
  "Haywood",
  "Heath",
  "Hector",
  "Henry",
  "Herb",
  "Herbert",
  "Heriberto",
  "Herman",
  "Herschel",
  "Hershel",
  "Hilario",
  "Hilton",
  "Hipolito",
  "Hiram",
  "Hobert",
  "Hollis",
  "Homer",
  "Hong",
  "Horace",
  "Horacio",
  "Hosea",
  "Houston",
  "Howard",
  "Hoyt",
  "Hubert",
  "Huey",
  "Hugh",
  "Hugo",
  "Humberto",
  "Hung",
  "Hunter",
  "Hyman",
  "Ian",
  "Ignacio",
  "Ike",
  "Ira",
  "Irvin",
  "Irving",
  "Irwin",
  "Isaac",
  "Isaiah",
  "Isaias",
  "Isiah",
  "Isidro",
  "Ismael",
  "Israel",
  "Isreal",
  "Issac",
  "Ivan",
  "Ivory",
  "Jacinto",
  "Jack",
  "Jackson",
  "Jacob",
  "Jacques",
  "Jae",
  "Jaime",
  "Jake",
  "Jamaal",
  "Jamal",
  "Jamar",
  "Jame",
  "Jamel",
  "James",
  "Jamey",
  "Jamie",
  "Jamison",
  "Jared",
  "Jarod",
  "Jarred",
  "Jarrett",
  "Jarrod",
  "Jarvis",
  "Jason",
  "Jasper",
  "Javier",
  "Jay",
  "Jayson",
  "Jed",
  "Jeff",
  "Jefferey",
  "Jefferson",
  "Jeffery",
  "Jeffrey",
  "Jeffry",
  "Jerald",
  "Jeramy",
  "Jere",
  "Jeremiah",
  "Jeremy",
  "Jermaine",
  "Jerold",
  "Jerome",
  "Jeromy",
  "Jerrell",
  "Jerrod",
  "Jerrold",
  "Jerry",
  "Jess",
  "Jesse",
  "Jessie",
  "Jim",
  "Jimmie",
  "Jimmy",
  "Joaquin",
  "Joe",
  "Joel",
  "Joesph",
  "Joey",
  "John",
  "Johnathan",
  "Johnathon",
  "Johnie",
  "Johnnie",
  "Johnny",
  "Johnson",
  "Jon",
  "Jonah",
  "Jonas",
  "Jonathan",
  "Jonathon",
  "Jordan",
  "Jorge",
  "Jose",
  "Josef",
  "Joseph",
  "Josh",
  "Joshua",
  "Josiah",
  "Jospeh",
  "Josue",
  "Juan",
  "Jude",
  "Judson",
  "Jules",
  "Julian",
  "Julio",
  "Julius",
  "Junior",
  "Justin",
  "Kareem",
  "Karl",
  "Keenan",
  "Keith",
  "Kelley",
  "Kelvin",
  "Ken",
  "Kendall",
  "Kendrick",
  "Keneth",
  "Kenneth",
  "Kennith",
  "Kenny",
  "Kent",
  "Kenton",
  "Kermit",
  "Keven",
  "Kevin",
  "Kieth",
  "King",
  "Kip",
  "Kirby",
  "Kirk",
  "Korey",
  "Kory",
  "Kraig",
  "Kristofer",
  "Kristopher",
  "Kurt",
  "Kurtis",
  "Kyle",
  "Lamar",
  "Lamont",
  "Lance",
  "Landon",
  "Lane",
  "Lanny",
  "Larry",
  "Laurence",
  "Lavern",
  "Lawerence",
  "Lawrence",
  "Lazaro",
  "Leandro",
  "Lee",
  "Leif",
  "Leland",
  "Lemuel",
  "Len",
  "Lenard",
  "Lenny",
  "Leo",
  "Leon",
  "Leonard",
  "Leonardo",
  "Leonel",
  "Leopoldo",
  "Leroy",
  "Les",
  "Lester",
  "Levi",
  "Lewis",
  "Lincoln",
  "Lino",
  "Linwood",
  "Lionel",
  "Lloyd",
  "Logan",
  "Lon",
  "Long",
  "Lonnie",
  "Lonny",
  "Loren",
  "Lorenzo",
  "Lou",
  "Louie",
  "Louis",
  "Lowell",
  "Loyd",
  "Lucas",
  "Luciano",
  "Lucien",
  "Lucio",
  "Lucius",
  "Luigi",
  "Luis",
  "Luke",
  "Luther",
  "Lyle",
  "Lyman",
  "Lyndon",
  "Lynwood",
  "Mac",
  "Mack",
  "Major",
  "Malcolm",
  "Malcom",
  "Malik",
  "Man",
  "Manual",
  "Manuel",
  "Marc",
  "Marcel",
  "Marcelino",
  "Marcellus",
  "Marcelo",
  "Marco",
  "Marcos",
  "Marcus",
  "Margarito",
  "Mariano",
  "Mario",
  "Mark",
  "Markus",
  "Marlin",
  "Marlon",
  "Marquis",
  "Marshall",
  "Martin",
  "Marty",
  "Marvin",
  "Mason",
  "Mathew",
  "Matt",
  "Matthew",
  "Maurice",
  "Mauricio",
  "Mauro",
  "Max",
  "Maximo",
  "Maxwell",
  "Maynard",
  "Mckinley",
  "Mel",
  "Melvin",
  "Merle",
  "Merlin",
  "Merrill",
  "Mervin",
  "Micah",
  "Michael",
  "Michal",
  "Michale",
  "Micheal",
  "Michel",
  "Mickey",
  "Miguel",
  "Mike",
  "Mikel",
  "Milan",
  "Miles",
  "Milford",
  "Millard",
  "Milo",
  "Milton",
  "Minh",
  "Miquel",
  "Mitch",
  "Mitchel",
  "Mitchell",
  "Modesto",
  "Mohamed",
  "Mohammad",
  "Mohammed",
  "Moises",
  "Monroe",
  "Monte",
  "Monty",
  "Morgan",
  "Morris",
  "Morton",
  "Mose",
  "Moses",
  "Moshe",
  "Murray",
  "Myles",
  "Myron",
  "Napoleon",
  "Nathan",
  "Nathanael",
  "Nathanial",
  "Nathaniel",
  "Neal",
  "Ned",
  "Neil",
  "Nelson",
  "Nestor",
  "Neville",
  "Newton",
  "Nicholas",
  "Nick",
  "Nickolas",
  "Nicky",
  "Nicolas",
  "Nigel",
  "Noah",
  "Noble",
  "Noe",
  "Noel",
  "Nolan",
  "Norbert",
  "Norberto",
  "Norman",
  "Normand",
  "Norris",
  "Numbers",
  "Octavio",
  "Odell",
  "Odis",
  "Olen",
  "Olin",
  "Oliver",
  "Ollie",
  "Omar",
  "Omer",
  "Oren",
  "Orlando",
  "Orval",
  "Orville",
  "Oscar",
  "Osvaldo",
  "Oswaldo",
  "Otha",
  "Otis",
  "Otto",
  "Owen",
  "Pablo",
  "Palmer",
  "Paris",
  "Parker",
  "Pasquale",
  "Patrick",
  "Paul",
  "Pedro",
  "Percy",
  "Perry",
  "Pete",
  "Peter",
  "Phil",
  "Philip",
  "Phillip",
  "Pierre",
  "Porfirio",
  "Porter",
  "Preston",
  "Prince",
  "Quentin",
  "Quincy",
  "Quinn",
  "Quintin",
  "Quinton",
  "Rafael",
  "Raleigh",
  "Ralph",
  "Ramiro",
  "Ramon",
  "Randal",
  "Randall",
  "Randell",
  "Randolph",
  "Randy",
  "Raphael",
  "Rashad",
  "Raul",
  "Ray",
  "Rayford",
  "Raymon",
  "Raymond",
  "Raymundo",
  "Reed",
  "Refugio",
  "Reggie",
  "Reginald",
  "Reid",
  "Reinaldo",
  "Renaldo",
  "Renato",
  "Rene",
  "Reuben",
  "Rex",
  "Rey",
  "Reyes",
  "Reynaldo",
  "Rhett",
  "Ricardo",
  "Rich",
  "Richard",
  "Richie",
  "Rick",
  "Rickey",
  "Rickie",
  "Ricky",
  "Rico",
  "Rigoberto",
  "Riley",
  "Rob",
  "Robbie",
  "Robby",
  "Robert",
  "Roberto",
  "Robin",
  "Robt",
  "Rocco",
  "Rocky",
  "Rod",
  "Roderick",
  "Rodger",
  "Rodney",
  "Rodolfo",
  "Rodrick",
  "Rodrigo",
  "Rogelio",
  "Roger",
  "Roland",
  "Rolando",
  "Rolf",
  "Rolland",
  "Roman",
  "Romeo",
  "Ron",
  "Ronald",
  "Ronnie",
  "Ronny",
  "Roosevelt",
  "Rory",
  "Rosario",
  "Roscoe",
  "Rosendo",
  "Ross",
  "Roy",
  "Royal",
  "Royce",
  "Ruben",
  "Rubin",
  "Rudolf",
  "Rudolph",
  "Rudy",
  "Rueben",
  "Rufus",
  "Rupert",
  "Russ",
  "Russel",
  "Russell",
  "Rusty",
  "Ryan",
  "Sal",
  "Salvador",
  "Salvatore",
  "Sam",
  "Sammie",
  "Sammy",
  "Samual",
  "Samuel",
  "Sanford",
  "Sang",
  "Santiago",
  "Santo",
  "Santos",
  "Saul",
  "Scot",
  "Scott",
  "Scottie",
  "Scotty",
  "Sean",
  "Sebastian",
  "Sergio",
  "Seth",
  "Seymour",
  "Shad",
  "Shane",
  "Shaun",
  "Shawn",
  "Shayne",
  "Shelby",
  "Sheldon",
  "Shelton",
  "Sherman",
  "Sherwood",
  "Shon",
  "Sid",
  "Sidney",
  "Silas",
  "Simon",
  "Sol",
  "Solomon",
  "Son",
  "Sonny",
  "Spencer",
  "Stan",
  "Stanford",
  "Stanley",
  "Stanton",
  "Stefan",
  "Stephan",
  "Stephen",
  "Sterling",
  "Steve",
  "Steven",
  "Stevie",
  "Stewart",
  "Stuart",
  "Sung",
  "Sydney",
  "Sylvester",
  "Tad",
  "Tanner",
  "Ted",
  "Teddy",
  "Teodoro",
  "Terence",
  "Terrance",
  "Terrell",
  "Terrence",
  "Terry",
  "Thad",
  "Thaddeus",
  "Thanh",
  "Theo",
  "Theodore",
  "Theron",
  "Thomas",
  "Thurman",
  "Tim",
  "Timmy",
  "Timothy",
  "Titus",
  "Tobias",
  "Toby",
  "Tod",
  "Todd",
  "Tom",
  "Tomas",
  "Tommie",
  "Tommy",
  "Toney",
  "Tony",
  "Tory",
  "Tracey",
  "Travis",
  "Trent",
  "Trenton",
  "Trevor",
  "Trey",
  "Trinidad",
  "Tristan",
  "Troy",
  "Truman",
  "Tuan",
  "Ty",
  "Tyler",
  "Tyree",
  "Tyrell",
  "Tyron",
  "Tyrone",
  "Tyson",
  "Ulysses",
  "Val",
  "Valentin",
  "Valentine",
  "Van",
  "Vance",
  "Vaughn",
  "Vern",
  "Vernon",
  "Vicente",
  "Victor",
  "Vince",
  "Vincent",
  "Vincenzo",
  "Virgil",
  "Virgilio",
  "Vito",
  "Von",
  "Wade",
  "Waldo",
  "Walker",
  "Wallace",
  "Wally",
  "Walter",
  "Walton",
  "Ward",
  "Warner",
  "Warren",
  "Waylon",
  "Wayne",
  "Weldon",
  "Wendell",
  "Werner",
  "Wes",
  "Wesley",
  "Weston",
  "Wilber",
  "Wilbert",
  "Wilbur",
  "Wilburn",
  "Wiley",
  "Wilford",
  "Wilfred",
  "Wilfredo",
  "Will",
  "Willard",
  "William",
  "Williams",
  "Willian",
  "Willie",
  "Willis",
  "Willy",
  "Wilmer",
  "Wilson",
  "Wilton",
  "Winford",
  "Winfred",
  "Winston",
  "Woodrow",
  "Wyatt",
  "Xavier",
  "Yong",
  "Young",
  "Zachariah",
  "Zachary",
  "Zachery",
  "Zack",
  "Zackary",
  "Zane",
]

erotica.girlsNames = [
  "Mary",
  "Patricia",
  "Linda",
  "Barbara",
  "Elizabeth",
  "Jennifer",
  "Maria",
  "Susan",
  "Margaret",
  "Dorothy",
  "Lisa",
  "Nancy",
  "Karen",
  "Betty",
  "Helen",
  "Sandra",
  "Donna",
  "Carol",
  "Ruth",
  "Sharon",
  "Michelle",
  "Laura",
  "Kimberly",
  "Deborah",
  "Jessica",
  "Shirley",
  "Cynthia",
  "Angela",
  "Melissa",
  "Brenda",
  "Amy",
  "Anna",
  "Virginia",
  "Kathleen",
  "Pamela",
  "Martha",
  "Debra",
  "Amanda",
  "Stephanie",
  "Carolyn",
  "Christine",
  "Marie",
  "Janet",
  "Catherine",
  "Frances",
  "Ann",
  "Joyce",
  "Diane",
  "Alice",
  "Julie",
  "Heather",
  "Teresa",
  "Doris",
  "Gloria",
  "Evelyn",
  "Jean",
  "Cheryl",
  "Mildred",
  "Katherine",
  "Joan",
  "Ashley",
  "Judith",
  "Rose",
  "Janice",
  "Kelly",
  "Nicole",
  "Judy",
  "Christina",
  "Kathy",
  "Theresa",
  "Beverly",
  "Denise",
  "Tammy",
  "Irene",
  "Jane",
  "Lori",
  "Rachel",
  "Marilyn",
  "Andrea",
  "Kathryn",
  "Louise",
  "Jacqueline",
  "Wanda",
  "Bonnie",
  "Julia",
  "Ruby",
  "Lois",
  "Tina",
  "Phyllis",
  "Norma",
  "Paula",
  "Diana",
  "Annie",
  "Lillian",
  "Emily",
  "Peggy",
  "Crystal",
  "Gladys",
  "Rita",
  "Dawn",
  "Connie",
  "Florence",
  "Tracy",
  "Edna",
  "Tiffany",
  "Carmen",
  "Rosa",
  "Cindy",
  "Grace",
  "Wendy",
  "Victoria",
  "Edith",
  "Kim",
  "Sherry",
  "Sylvia",
  "Josephine",
  "Thelma",
  "Shannon",
  "Sheila",
  "Ethel",
  "Ellen",
  "Elaine",
  "Marjorie",
  "Carrie",
  "Charlotte",
  "Monica",
  "Esther",
  "Pauline",
  "Emma",
  "Juanita",
  "Anita",
  "Rhonda",
  "Hazel",
  "Amber",
  "Eva",
  "Debbie",
  "April",
  "Leslie",
  "Clara",
  "Lucille",
  "Joanne",
  "Eleanor",
  "Valerie",
  "Danielle",
  "Megan",
  "Alicia",
  "Suzanne",
  "Michele",
  "Gail",
  "Bertha",
  "Darlene",
  "Veronica",
  "Jill",
  "Erin",
  "Geraldine",
  "Lauren",
  "Cathy",
  "Joann",
  "Lorraine",
  "Lynn",
  "Sally",
  "Regina",
  "Erica",
  "Beatrice",
  "Dolores",
  "Bernice",
  "Audrey",
  "Yvonne",
  "Annette",
  "June",
  "Samantha",
  "Marion",
  "Dana",
  "Stacy",
  "Ana",
  "Renee",
  "Ida",
  "Vivian",
  "Roberta",
  "Holly",
  "Brittany",
  "Melanie",
  "Loretta",
  "Yolanda",
  "Jeanette",
  "Laurie",
  "Katie",
  "Kristen",
  "Vanessa",
  "Alma",
  "Sue",
  "Elsie",
  "Beth",
  "Jeanne",
  "Vicki",
  "Carla",
  "Tara",
  "Rosemary",
  "Eileen",
  "Terri",
  "Gertrude",
  "Lucy",
  "Tonya",
  "Ella",
  "Stacey",
  "Wilma",
  "Gina",
  "Kristin",
  "Natalie",
  "Agnes",
  "Vera",
  "Charlene",
  "Bessie",
  "Delores",
  "Melinda",
  "Pearl",
  "Arlene",
  "Maureen",
  "Colleen",
  "Allison",
  "Tamara",
  "Joy",
  "Georgia",
  "Constance",
  "Lillie",
  "Claudia",
  "Jackie",
  "Marcia",
  "Tanya",
  "Nellie",
  "Minnie",
  "Marlene",
  "Heidi",
  "Glenda",
  "Lydia",
  "Viola",
  "Courtney",
  "Marian",
  "Stella",
  "Caroline",
  "Dora",
  "Jo",
  "Vickie",
  "Mattie",
  "Maxine",
  "Irma",
  "Mabel",
  "Marsha",
  "Myrtle",
  "Lena",
  "Christy",
  "Deanna",
  "Patsy",
  "Hilda",
  "Gwendolyn",
  "Jennie",
  "Nora",
  "Margie",
  "Nina",
  "Cassandra",
  "Leah",
  "Penny",
  "Kay",
  "Priscilla",
  "Naomi",
  "Carole",
  "Brandy",
  "Olga",
  "Billie",
  "Dianne",
  "Leona",
  "Jenny",
  "Felicia",
  "Sonia",
  "Miriam",
  "Velma",
  "Becky",
  "Bobbie",
  "Violet",
  "Kristina",
  "Toni",
  "Misty",
  "Mae",
  "Shelly",
  "Daisy",
  "Ramona",
  "Sherri",
  "Erika",
  "Katrina",
  "Claire",
  "Lindsey",
  "Lindsay",
  "Geneva",
  "Guadalupe",
  "Belinda",
  "Margarita",
  "Sheryl",
  "Cora",
  "Faye",
  "Ada",
  "Natasha",
  "Sabrina",
  "Isabel",
  "Marguerite",
  "Hattie",
  "Harriet",
  "Molly",
  "Cecilia",
  "Kristi",
  "Brandi",
  "Blanche",
  "Sandy",
  "Rosie",
  "Iris",
  "Eunice",
  "Angie",
  "Inez",
  "Lynda",
  "Madeline",
  "Amelia",
  "Alberta",
  "Genevieve",
  "Monique",
  "Jodi",
  "Janie",
  "Maggie",
  "Kayla",
  "Sonya",
  "Jan",
  "Kristine",
  "Candace",
  "Fannie",
  "Maryann",
  "Opal",
  "Alison",
  "Yvette",
  "Melody",
  "Luz",
  "Susie",
  "Olivia",
  "Flora",
  "Shelley",
  "Kristy",
  "Mamie",
  "Lula",
  "Lola",
  "Verna",
  "Beulah",
  "Antoinette",
  "Candice",
  "Juana",
  "Jeannette",
  "Pam",
  "Kelli",
  "Hannah",
  "Whitney",
  "Bridget",
  "Karla",
  "Celia",
  "Latoya",
  "Patty",
  "Shelia",
  "Gayle",
  "Della",
  "Vicky",
  "Lynne",
  "Sheri",
  "Marianne",
  "Kara",
  "Jacquelyn",
  "Erma",
  "Blanca",
  "Myra",
  "Leticia",
  "Pat",
  "Krista",
  "Roxanne",
  "Angelica",
  "Robyn",
  "Adrienne",
  "Rosalie",
  "Alexandra",
  "Brooke",
  "Bethany",
  "Sadie",
  "Bernadette",
  "Traci",
  "Jody",
  "Kendra",
  "Jasmine",
  "Nichole",
  "Rachael",
  "Chelsea",
  "Mable",
  "Ernestine",
  "Muriel",
  "Marcella",
  "Elena",
  "Krystal",
  "Angelina",
  "Nadine",
  "Kari",
  "Estelle",
  "Dianna",
  "Paulette",
  "Lora",
  "Mona",
  "Doreen",
  "Rosemarie",
  "Angel",
  "Desiree",
  "Antonia",
  "Hope",
  "Ginger",
  "Janis",
  "Betsy",
  "Christie",
  "Freda",
  "Mercedes",
  "Meredith",
  "Lynette",
  "Teri",
  "Cristina",
  "Eula",
  "Leigh",
  "Meghan",
  "Sophia",
  "Eloise",
  "Rochelle",
  "Gretchen",
  "Cecelia",
  "Raquel",
  "Henrietta",
  "Alyssa",
  "Jana",
  "Gwen",
  "Kerry",
  "Jenna",
  "Tricia",
  "Laverne",
  "Olive",
  "Tasha",
  "Silvia",
  "Elvira",
  "Casey",
  "Delia",
  "Sophie",
  "Kate",
  "Patti",
  "Lorena",
  "Kellie",
  "Sonja",
  "Lila",
  "Lana",
  "Darla",
  "May",
  "Mindy",
  "Essie",
  "Mandy",
  "Lorene",
  "Elsa",
  "Josefina",
  "Jeannie",
  "Miranda",
  "Dixie",
  "Lucia",
  "Marta",
  "Faith",
  "Lela",
  "Johanna",
  "Shari",
  "Camille",
  "Tami",
  "Shawna",
  "Elisa",
  "Ebony",
  "Melba",
  "Ora",
  "Nettie",
  "Tabitha",
  "Winifred",
  "Kristie",
  "Marina",
  "Alisha",
  "Aimee",
  "Rena",
  "Myrna",
  "Marla",
  "Tammie",
  "Latasha",
  "Bonita",
  "Patrice",
  "Ronda",
  "Sherrie",
  "Addie",
  "Francine",
  "Deloris",
  "Stacie",
  "Adriana",
  "Cheri",
  "Abigail",
  "Celeste",
  "Jewel",
  "Cara",
  "Adele",
  "Rebekah",
  "Lucinda",
  "Dorthy",
  "Effie",
  "Trina",
  "Reba",
  "Sallie",
  "Aurora",
  "Lenora",
  "Etta",
  "Lottie",
  "Kerri",
  "Trisha",
  "Nikki",
  "Estella",
  "Francisca",
  "Josie",
  "Tracie",
  "Marissa",
  "Karin",
  "Brittney",
  "Janelle",
  "Lourdes",
  "Laurel",
  "Helene",
  "Fern",
  "Elva",
  "Corinne",
  "Kelsey",
  "Ina",
  "Bettie",
  "Elisabeth",
  "Aida",
  "Caitlin",
  "Ingrid",
  "Iva",
  "Eugenia",
  "Christa",
  "Goldie",
  "Cassie",
  "Maude",
  "Jenifer",
  "Therese",
  "Frankie",
  "Lorna",
  "Janette",
  "Latonya",
  "Candy",
  "Consuelo",
  "Tamika",
  "Rosetta",
  "Debora",
  "Cherie",
  "Polly",
  "Dina",
  "Jewell",
  "Fay",
  "Jillian",
  "Dorothea",
  "Nell",
  "Trudy",
  "Esperanza",
  "Patrica",
  "Kimberley",
  "Shanna",
  "Helena",
  "Carolina",
  "Cleo",
  "Stefanie",
  "Ola",
  "Janine",
  "Mollie",
  "Lupe",
  "Alisa",
  "Maribel",
  "Susanne",
  "Bette",
  "Susana",
  "Elise",
  "Cecile",
  "Isabelle",
  "Lesley",
  "Jocelyn",
  "Paige",
  "Joni",
  "Rachelle",
  "Leola",
  "Daphne",
  "Alta",
  "Ester",
  "Petra",
  "Graciela",
  "Imogene",
  "Jolene",
  "Keisha",
  "Lacey",
  "Glenna",
  "Gabriela",
  "Keri",
  "Ursula",
  "Lizzie",
  "Kirsten",
  "Shana",
  "Adeline",
  "Mayra",
  "Jayne",
  "Jaclyn",
  "Gracie",
  "Sondra",
  "Carmela",
  "Marisa",
  "Rosalind",
  "Charity",
  "Tonia",
  "Beatriz",
  "Marisol",
  "Clarice",
  "Jeanine",
  "Sheena",
  "Angeline",
  "Frieda",
  "Lily",
  "Shauna",
  "Millie",
  "Claudette",
  "Cathleen",
  "Angelia",
  "Gabrielle",
  "Autumn",
  "Katharine",
  "Summer",
  "Jodie",
  "Staci",
  "Lea",
  "Christi",
  "Justine",
  "Elma",
  "Luella",
  "Margret",
  "Dominique",
  "Socorro",
  "Martina",
  "Margo",
  "Mavis",
  "Callie",
  "Bobbi",
  "Maritza",
  "Lucile",
  "Leanne",
  "Jeannine",
  "Deana",
  "Aileen",
  "Lorie",
  "Ladonna",
  "Willa",
  "Manuela",
  "Gale",
  "Selma",
  "Dolly",
  "Sybil",
  "Abby",
  "Lara",
  "Dale",
  "Ivy",
  "Dee",
  "Winnie",
  "Marcy",
  "Luisa",
  "Jeri",
  "Magdalena",
  "Ofelia",
  "Meagan",
  "Audra",
  "Matilda",
  "Leila",
  "Cornelia",
  "Bianca",
  "Simone",
  "Bettye",
  "Randi",
  "Virgie",
  "Latisha",
  "Barbra",
  "Georgina",
  "Eliza",
  "Leann",
  "Bridgette",
  "Rhoda",
  "Haley",
  "Adela",
  "Nola",
  "Bernadine",
  "Flossie",
  "Ila",
  "Greta",
  "Ruthie",
  "Nelda",
  "Minerva",
  "Lilly",
  "Terrie",
  "Letha",
  "Hilary",
  "Estela",
  "Valarie",
  "Brianna",
  "Rosalyn",
  "Earline",
  "Catalina",
  "Ava",
  "Mia",
  "Clarissa",
  "Lidia",
  "Corrine",
  "Alexandria",
  "Concepcion",
  "Tia",
  "Sharron",
  "Rae",
  "Dona",
  "Ericka",
  "Jami",
  "Elnora",
  "Chandra",
  "Lenore",
  "Neva",
  "Marylou",
  "Melisa",
  "Tabatha",
  "Serena",
  "Avis",
  "Allie",
  "Sofia",
  "Jeanie",
  "Odessa",
  "Nannie",
  "Harriett",
  "Loraine",
  "Penelope",
  "Milagros",
  "Emilia",
  "Benita",
  "Allyson",
  "Ashlee",
  "Tania",
  "Esmeralda",
  "Karina",
  "Eve",
  "Pearlie",
  "Zelma",
  "Malinda",
  "Noreen",
  "Tameka",
  "Saundra",
  "Hillary",
  "Amie",
  "Althea",
  "Rosalinda",
  "Lilia",
  "Alana",
  "Gay",
  "Clare",
  "Alejandra",
  "Elinor",
  "Lorrie",
  "Jerri",
  "Darcy",
  "Earnestine",
  "Carmella",
  "Taylor",
  "Noemi",
  "Marcie",
  "Liza",
  "Annabelle",
  "Louisa",
  "Earlene",
  "Mallory",
  "Carlene",
  "Nita",
  "Selena",
  "Tanisha",
  "Katy",
  "Julianne",
  "Lakisha",
  "Edwina",
  "Maricela",
  "Margery",
  "Kenya",
  "Dollie",
  "Roxie",
  "Roslyn",
  "Kathrine",
  "Nanette",
  "Charmaine",
  "Lavonne",
  "Ilene",
  "Kris",
  "Tammi",
  "Suzette",
  "Corine",
  "Kaye",
  "Chrystal",
  "Lina",
  "Deanne",
  "Lilian",
  "Juliana",
  "Aline",
  "Luann",
  "Kasey",
  "Maryanne",
  "Evangeline",
  "Colette",
  "Melva",
  "Lawanda",
  "Yesenia",
  "Nadia",
  "Madge",
  "Kathie",
  "Ophelia",
  "Valeria",
  "Nona",
  "Mitzi",
  "Mari",
  "Georgette",
  "Claudine",
  "Fran",
  "Alissa",
  "Roseann",
  "Lakeisha",
  "Susanna",
  "Reva",
  "Deidre",
  "Chasity",
  "Sheree",
  "Carly",
  "Elvia",
  "Alyce",
  "Deirdre",
  "Gena",
  "Briana",
  "Araceli",
  "Katelyn",
  "Rosanne",
  "Wendi",
  "Tessa",
  "Berta",
  "Marva",
  "Imelda",
  "Marietta",
  "Marci",
  "Leonor",
  "Arline",
  "Sasha",
  "Madelyn",
  "Janna",
  "Juliette",
  "Deena",
  "Aurelia",
  "Josefa",
  "Augusta",
  "Liliana",
  "Lessie",
  "Amalia",
  "Savannah",
  "Anastasia",
  "Vilma",
  "Natalia",
  "Rosella",
  "Lynnette",
  "Corina",
  "Alfreda",
  "Leanna",
  "Amparo",
  "Coleen",
  "Tamra",
  "Aisha",
  "Wilda",
  "Karyn",
  "Cherry",
  "Queen",
  "Maura",
  "Mai",
  "Evangelina",
  "Rosanna",
  "Hallie",
  "Erna",
  "Enid",
  "Mariana",
  "Lacy",
  "Juliet",
  "Freida",
  "Madeleine",
  "Mara",
  "Hester",
  "Cathryn",
  "Lelia",
  "Casandra",
  "Bridgett",
  "Angelita",
  "Jannie",
  "Dionne",
  "Annmarie",
  "Katina",
  "Beryl",
  "Phoebe",
  "Millicent",
  "Katheryn",
  "Diann",
  "Carissa",
  "Maryellen",
  "Liz",
  "Lauri",
  "Helga",
  "Gilda",
  "Rhea",
  "Marquita",
  "Hollie",
  "Tisha",
  "Tamera",
  "Angelique",
  "Francesca",
  "Britney",
  "Kaitlin",
  "Florine",
  "Rowena",
  "Reyna",
  "Twila",
  "Janell",
  "Ines",
  "Concetta",
  "Bertie",
  "Alba",
  "Brigitte",
  "Alyson",
  "Vonda",
  "Elba",
  "Noelle",
  "Letitia",
  "Kitty",
  "Deann",
  "Brandie",
  "Louella",
  "Leta",
  "Felecia",
  "Sharlene",
  "Lesa",
  "Beverley",
  "Isabella",
  "Herminia",
  "Terra",
  "Celina",
]

erotica.cocktails = [
  "Cosmopolitan",
  "Bloody Mary",
  "Blue Lagoon",
  "Apple Martini",
  "Metropolis",
  "Serena",
  "Long Island Iced Tea",
  "Berry Me in the Sand",
  "360 Degrees",
  "Vodka Sunrise",
  "Mind Eraser",
  "White Russian",
  "Sea Breeze",
  "Lime Rickey",
  "Black Russian",
  "Screwdriver",
  "Kremlin Colonel",
  "Sex on the Beach",
  "Mudslide",
  "Autumn in New York",
  "Blue Hawaii",
  "Napa Sun",
  "One Night Stand",
  "Greyhound",
  "Black Bison",
  "Pomegranate Martini",
  "Samantha",
  "Spider's Kiss",
  "Tuxedo",
  "Caipiroska",
  "Ice Pick",
  "Tropical Itch",
  "Rum Swizzle",
  "Piña Colada",
  "Daiquiri",
  "Macau",
  "Mai Tai",
  "Bahama Mama",
  "Strawberry Basil Mojito",
  "Malibu Breeze",
  "Devil's Poison",
  "Pink Frost",
  "Egg Nog",
  "Nude Beach",
  "Pineapple Mai Tai",
  "Creole Splash",
  "Creepy Crawler Punch",
  "Quicky",
  "Jamaican Winter",
  "Hurricane",
  "Banana Daiquiri",
  "Spice Night",
  "Long Beach Ice Tea",
  "Zombie",
  "Watermelon Granita",
  "The Crimson Tide",
  "Tom and Jerry",
  "Boston Sidecar",
  "Cuba Libre",
  "Hairy Virgin",
  "Painkiller",
  "Orange Bomber",
  "Creole Splash",
  "Heatwave",
  "Geisha Girl",
  "Pink Lady",
  "Mickey Slim",
  "Punch",
  "Blue Motorcycle",
  "Paradise",
  "Tom Collins",
  "Gimlet",
  "Salty Dog",
  "Lime Rickey",
  "Vesper Martini",
  "Newport Cooler",
  "Dragonfly",
  "Nightmare",
  "Deep Sea",
  "Napoleon",
  "White Lady",
  "Hanky Panky",
  "Gin and Tonic",
  "Pink Gin",
  "Snowball",
  "Fallen Angel",
  "Emerald Forest",
  "Pink Panther",
  "Orange Blossom",
  "Earthquake",
  "Irish Sour",
  "Hawaiian Cocktail",
  "Summer Gin Punch",
  "Royal Arrival",
  "My Fair Lady",
  "Peach Mojito",
  "Red Sangria",
  "Singapore Sling",
  "Newport Cooler",
  "Boston Sidecar",
  "Between the Sheets",
  "Aphrodisiac",
  "Vanderbilt Cocktail",
  "Depth Bomb",
  "Corpse Reviver",
  "Vanity Fair",
  "Summer Slush",
  "Brandy Alexander",
  "City Slicker",
  "Bloody Black Currant",
  "Stinger",
  "Panama",
  "Cafe Zurich",
  "Brandy",
  "Orgasm",
  "Manhattan",
  "Four Score",
  "Aviation",
  "Sparkling Spring Punch",
  "After Dark",
  "Mexican Martini",
  "Margarita",
  "Apple Bob",
  "Long Beach Ice Tea",
  "Prairie Fire",
  "Navy Seal",
  "Calabatini",
  "Red Hot Mama",
  "Blue Stampede",
  "Citrico Snowflake",
  "Paloma",
  "Grenada",
  "Firecracker",
  "The Orange Turf",
  "Tequila Sunset",
  "The One Cheek Sneak",
  "Joker's Tea",
  "Icebreaker",
  "Three Amigos",
  "Frostbite",
  "Gold Rush",
  "The Prickly Margarita",
  "Tequila Sunrise",
  "Four Leaf Cloverita",
  "El Diablo",
  "Tequila Tangerine Dream",
  "Massacre",
  "Blue Voodoo Doll",
  "Arizona Margarita",
  "Paralyzer",
  "Tequila Slammer",
  "Matador",
  "Tonic and Tequila",
  "Bloody Aztec",
  "Jungle Juice",
  "Choking Hazard",
  "Manhattan",
  "Rusty Nail",
  "Seven and Seven",
  "Godfather",
  "Bourbon Cobbler",
  "Red Death",
  "Sazerac",
  "Quick Kick",
  "Mr. Big",
  "Canadian Club Old Fashioned",
  "Cork Comfort",
  "Renegade",
  "The Dublin Apple",
  "Hiram Walker",
  "Good Night Special",
  "Deadly Nightshade",
  "Jimmy Russel's Mint Julep",
  "Vancouver Cocktail",
  "The Steeler",
  "Spirited Punch",
  "Smoky Martini",
  "Basil Hayden Wish",
  "Merry Irishman",
  "Admiral",
  "Blood and Sand",
  "Cherries Jubilee",
  "Heart of Fire",
  "Royal Widow",
  "John Collins",
  "Flirtini",
  "Mimosa",
  "Champagne Cocktail",
  "White Wine Sangria",
  "Quaker City Cooler",
  "Nelson's Blood",
  "Sparkling Spring Punch",
  "Bellini",
  "Blood Red Sangria",
  "Kentucky Champagne",
  "Sour Witch",
  "Golden Glamour",
  "The Bubbly Apricot",
  "French 75",
  "Chicago Cocktail",
  "Wine Cooler",
  "Savoy Affair",
  "Prince of Wales",
  "Ruby Dutchess",
  "Half and Half",
  "Spiced Tea Holiday Punch",
  "Chocolate Velvet",
  "Thriller",
  "Artillery Punch",
  "Bambus",
  "Blue Wave",
  "Dancing Dutchman",
  "Buckk's Fizz",
  "Champagne Flamingo",
  "Elderflower Cocktail",
  "Dutch Tulip",
  "Pomegranate Pineapple Fireworks",
  "Kir Royale",
  "Rouge Noir",
  "Strawberry Flapper",
  "Raspberry Bellini",
  "Waterloo Sunset",
  "Sangria",
  "Spanish Sangria",
  "Strawberry Ginger Martini",
  "Alabama Slammer",
  "Bewitched",
  "Mind Eraser",
  "Cadillac Margarita",
  "Passion",
  "Blood Orange Freeze",
  "Naughty Holiday Punches",
  "Chocolate Mint",
  "Orange Crush",
  "Night and Day",
  "Leprechaun Martini",
  "Monkey Fizz",
  "Butterscotch Martini",
  "Dirty Mother",
  "Kahlua",
  "Irish Car Bomb",
  "White Russian",
  "Grasshopper",
  "Lemon Drop",
  "Kamikaze",
  "Golden Dream",
  "Electric Martini",
  "Blue Eyes",
  "Spanish Crown",
  "Melon Ball",
  "Nuclear Martini",
  "Silverlake Slip",
  "Italian Sunset",
  "Godmother",
  "Jellybean",
  "Cranberry Citrus Swizzle",
  "Sidecarriage",
  "Poinsettia Cocktail",
]


